openapi: 3.0.3
info:
  title: Projeto do SENAI Jandira - Professor Marcel
  description: |-
   API destinada a controle de uma locadora de filmes
  termsOfService: http://swagger.io/terms/
  contact:
    email: nathansilvacosta2303@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
paths:
  /v1/locadora/filme:
    get:
      tags:
        - filme
      summary: Busca todos os filmes
      description: Retorna uma lista de filmes
      responses:
        '200':
          description: Requisição bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filme'
        '404':
          description: Não foram encontrados dados de retorno
        '500':
          description: Não foi possível processar a requisição devido a erros internos no servidor (CONTROLLER ou MODELAGEM DE DADOS)
    post:
      tags:
        - filme
      summary: Cria um filme
      description: Cria um novo filme
      requestBody:
        description: Cria um novo filme
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Filme'
        required: true
      responses:
        '201':
          description: Item criado com sucesso
        '400':
          description: Não foi possível processar a requisição pois existem campos obrigatórios que devem ser encaminhados e antedidos conforme documentação
        '415':
          description: Não foi possível processar a requisição, pois o tipo de dados enviado no corpo deve ser JSON
        '500':
          description: Não foi possível processar a requisição devido a erros internos no servidor (CONTROLLER ou MODELAGEM DE DADOS)
  /v1/locadora/filme/{id}:
    get:
      tags:
        - filme
      summary: Busca um filme pelo ID
      description: Retorna um filme pelo ID
      parameters:
        - name: id
          in: path
          description: ID do filme de retorno
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Requisição bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filme'          
        '400':
          description: (referente a validação do ID) - Não foi possível processar a requisição pois existem campos obrigatórios que devem ser encaminhados e antedidos conforme documentação
        '404':
          description: Não foram encontrados dados de retorno
        '500':
          description: Não foi possível processar a requisição devido a erros internos no servidor (CONTROLLER ou MODELAGEM DE DADOS)
    put:
      tags:
        - filme
      summary: Atualiza um filme existente
      description: Atualiza um filme existente pelo ID
      parameters:
        - name: id
          in: path
          description: ID do filme de retorno
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Atualiza um filme existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Filme'
        required: true
      responses:
        '200':
          description: Item atualizado com sucesso
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
    delete:
      tags:
        - filme
      summary: Delete aluno
      description: Excluir um aluno
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
components:
  schemas:
    Filme:
      type: object
      required:
        - nome
        - duracao
        - orcamento
        - capa
      properties:
        id:
          type: integer
        nome:
          type: string
        sinopse:
          type: string
        data_lancamento:
          type: string
        duracao:
          type: string
        orcamento:
          type: number
        trailer:
          type: string
        capa:
          type: string
    Genero:
      type: object
      required:
        - nome
      properties:
        id:
          type: integer
        nome:
          type: string
    Cargo:
      type: object
      required:
        - nome
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
    Producao:
      type: object
      required:
        - nome
        - pais_origem
      properties:
        id:
          type: integer
        nome:
          type: string
        pais_origem:
          type: string
        fundacao:
          type: string
        site:
          type: string
    FormatoAudiovisual:
      type: object
      required:
        - nome
      properties:
        id:
          type: integer
        nome:
          type: string
    Distribuidora:
      type: object
      required:
        - nome
        - pais_origem
      properties:
        id:
          type: integer
        nome:
          type: string
        pais_origem:
          type: string
        site:
          type: string
    Personagem:
      type: object
      required:
        - nome
        - imagem
        - papel
      properties:
        id:
          type: integer
        nome:
          type: string
        imagem:
          type: string
        idade:
          type: integer
        descricao:
          type: string
        papel:
          type: string
